---

# cause tmp dir cleaned after some time
- name: create root app dir
  file:
    path: '/root/apps/'
    state: directory
    mode: 0755

- name: 'add canonical partners repo'
  apt_repository:
    repo: 'deb http://archive.canonical.com/ubuntu {{ ansible_distribution_release }} partner'

# commented - no repo for 16.04
#
#- name: 'add Cool Reader repo'
#  apt_repository:
#    repo: 'ppa:vovansrnd/coolreader'

- name: add sublime repo
  apt_repository:
    repo: 'ppa:webupd8team/sublime-text-3'

- name: add asciinema repo
  apt_repository:
    repo: 'ppa:zanchey/asciinema'

- name: add spotify key
  apt_key:
    keyserver: 'hkp://keyserver.ubuntu.com:80'
    id: 'BBEBDCB318AD50EC6865090613B00F1FD2C19886'

- name: add spotify repo
  apt_repository:
    repo: 'deb http://repository.spotify.com stable non-free'

# latest version fix Copy-paste issue
# Version: 1.2.0~rcgit-15+982+next+201610270632~ubuntu16.04.1
- name: add remmina repo
  apt_repository:
    repo: 'ppa:remmina-ppa-team/remmina-next'

#- name: add chrome key
#  apt_key:
#    url: 'https://dl-ssl.google.com/linux/linux_signing_key.pub'
#
# TODO 404 not found
#- name: add chrome repo
#  apt_repository:
#    repo: 'deb http://dl.google.com/linux/chrome/deb/ stable main'

- name: update apt-get
  apt: update_cache=yes

# check current package version:
# dpkg -s <package>

- name: install basic packages
  apt: name={{item}} state=latest
  with_items:
    - ntp
    - curl
    - openssl
    - libcurl4-openssl-dev
    - zlib1g-dev
    - libssl-dev
    - libssl-doc
    - libreadline-dev
    - libyaml-dev
    - libffi-dev
    - libsqlite3-dev
    - sqlite3
    - libxml2-dev
    - libxslt1-dev
    - libaugeas-dev
    - build-essential
    - wget
    - python-software-properties
    - bash
    - htop
    - iotop
    - iftop
    - traceroute
    - vim
    - tmux

- name: install applications
  apt: name={{item}} state=present
  with_items:
    - git
    - skype
#    - google-chrome-stable
    - filezilla
    - sublime-text-installer
    - xpad # sticky notes
    - fbreader # text reader
    - clementine # music player
    - remmina # RDP
    - remmina-plugin-rdp
    - vlc # video player
    - wireshark # network sniffer
    - wavemon # wi-fi signal monitoring
    - inkscape # graphic editor
    - gimp # graphic editor
    - xdot # graph viewer
    - kazam # screencast
    - shutter # editor
    - asciinema # terminal recorder
    - spotify-client
    - unity-tweak-tool # to disable unity animations - http://askubuntu.com/a/689612
    - p7zip-full


# install redis desktop manager
#------------------------------

# "Dependency is not satisfiable: libicu52\n"} Fixed in 0.9
#
#- name: download redis manager deb
#  get_url:
#    url: 'https://github.com/uglide/RedisDesktopManager/releases/download/0.8.3/redis-desktop-manager_0.8.3-120_amd64.deb'
#    dest: '/root/apps/redis-desktop-manager_0.8.3-120_amd64.deb'
#
#- name: install redis manager package
#  apt:
#    deb: '/root/apps/redis-desktop-manager_0.8.3-120_amd64.deb'
#    state: present


# install chrome
#------------------------------

- name: download chrome deb
  get_url:
    url: 'https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb'
    dest: '/root/apps/google-chrome-stable_current_amd64.deb'

- name: install chrome
  apt:
    deb: '/root/apps/google-chrome-stable_current_amd64.deb'
    state: present


# install dragon disk (CEPH / S3)
#------------------------------

#- name: download dragon disk deb
#  get_url:
#    url: 'http://download.dragondisk.com/dragondisk_1.0.5-0ubuntu_amd64.deb'
#    dest: '/root/apps/dragondisk_1.0.5-0ubuntu_amd64.deb'
#
## TODO 404 not found
#
#- name: install dragon disk
#  apt:
#    deb: '/root/apps/dragondisk_1.0.5-0ubuntu_amd64.deb'
#    state: present


# install robomongo
#------------------------------

- name: create dir for robomongo binaries
  file:
    path: '/opt/robomongo'
    state: directory
    mode: 0755

- name: add robomongo to system path
  copy:
    dest: '/etc/profile.d/robomongo.sh'
    content: 'export PATH=/opt/robomongo/robomongo-0.9.0-rc10-linux-x86_64-33c89ea/bin/:$PATH'

- name: download robomongo zip
  get_url:
    url: 'https://download.robomongo.org/0.9.0-rc10/linux/robomongo-0.9.0-rc10-linux-x86_64-33c89ea.tar.gz'
    dest: '/root/apps/robomongo-0.9.0-rc10-linux-x86_64-33c89ea.tar.gz'

- name: "unzip robomongo"
  unarchive:
    src: "/root/apps/robomongo-0.9.0-rc10-linux-x86_64-33c89ea.tar.gz"
    dest: "/opt/robomongo"
    copy: no


# add default template file in file manager

- name: "add libreoffice template"
  copy:
    src: "files/ubuntu_file_templates/Empty Document.odt"
    dest: "/home/artem/Templates/Empty Document.odt"
    owner: "{{ home_user }}"
    group: "{{ home_user }}"

