---

- name: add canonical partners repo
  apt_repository:
    repo: 'deb http://archive.canonical.com/ubuntu {{ ansible_distribution_release }} partner'

- name: update apt-get
  apt: update_cache=yes

- name: install basic packages
  apt: name={{item}} state=latest
  with_items:
    - ntp
    - curl
    - openssl
    - libcurl4-openssl-dev
    - zlib1g-dev
    - libssl-dev
    - libssl-doc
    - libreadline-dev
    - libyaml-dev
    - libffi-dev
    - libsqlite3-dev
    - sqlite3
    - libxml2-dev
    - libxslt1-dev
    - libaugeas-dev
    - build-essential
    - wget
    - python-software-properties
    - bash

- name: install applications
  apt: name={{item}} state=present
  with_items:
    - git
    - htop
    - iotop
    - iftop
    - traceroute
    - vim
    - tmux
    - skype
    - clementine # music player
    - remmina # RDP
    - vlc # video player
    - wireshark # network sniffer
    - wavemon # wi-fi signal monitoring
    - inkscape # graphic editor
    - gimp # graphic editor
    - xdot # graph viewer
    - kazam # screencast
    - shutter # editor
