---

- name: 'add canonical partners repo'
  apt_repository:
    repo: 'deb http://archive.canonical.com/ubuntu {{ ansible_distribution_release }} partner'

- name: 'add Cool Reader repo'
  apt_repository:
    repo: 'ppa:vovansrnd/coolreader'

- name: add sublime repo
  apt_repository:
    repo: 'ppa:webupd8team/sublime-text-3'

- name: add chrome key
  apt_key:
    url: 'https://dl-ssl.google.com/linux/linux_signing_key.pub'

# TODO 404 not found
#- name: add chrome repo
#  apt_repository:
#    repo: 'deb http://dl.google.com/linux/chrome/deb/ stable main'

- name: update apt-get
  apt: update_cache=yes

- name: install basic packages
  apt: name={{item}} state=latest
  with_items:
    - ntp
    - curl
    - openssl
    - libcurl4-openssl-dev
    - zlib1g-dev
    - libssl-dev
    - libssl-doc
    - libreadline-dev
    - libyaml-dev
    - libffi-dev
    - libsqlite3-dev
    - sqlite3
    - libxml2-dev
    - libxslt1-dev
    - libaugeas-dev
    - build-essential
    - wget
    - python-software-properties
    - bash
    - htop
    - iotop
    - iftop
    - traceroute
    - vim
    - tmux

- name: install applications
  apt: name={{item}} state=present
  with_items:
    - git
    - skype
    - google-chrome-stable
    - filezilla
    - sublime-text-installer
    - fbreader # text reader
    - clementine # music player
    - remmina # RDP
    - vlc # video player
    - wireshark # network sniffer
    - wavemon # wi-fi signal monitoring
    - inkscape # graphic editor
    - gimp # graphic editor
    - xdot # graph viewer
    - kazam # screencast
    - shutter # editor


# install redis desktop manager
#------------------------------

- name: download redis manager deb
  get_url:
    url: 'https://github.com/uglide/RedisDesktopManager/releases/download/0.8.3/redis-desktop-manager_0.8.3-120_amd64.deb'
    dest: '/tmp/redis-desktop-manager_0.8.3-120_amd64.deb'

- name: install redis manager package
  apt:
    deb: '/tmp/redis-desktop-manager_0.8.3-120_amd64.deb'
    state: present


# install robomongo
#------------------------------

- name: create dir for robomongo binaries
  file:
    path: '/opt/robomongo'
    state: directory
    mode: 0755

- name: add robomongo to system path
  copy:
    dest: '/etc/profile.d/robomongo.sh'
    content: 'export PATH=/opt/robomongo/robomongo-0.9.0-rc10-linux-x86_64-33c89ea/bin/:$PATH'

- name: download robomongo zip
  get_url:
    url: 'https://download.robomongo.org/0.9.0-rc10/linux/robomongo-0.9.0-rc10-linux-x86_64-33c89ea.tar.gz'
    dest: '/tmp/robomongo-0.9.0-rc10-linux-x86_64-33c89ea.tar.gz'

- name: "unzip robomongo"
  unarchive:
    src: "/tmp/robomongo-0.9.0-rc10-linux-x86_64-33c89ea.tar.gz"
    dest: "/opt/robomongo"
    copy: no


