---

# https://github.com/angstwad/docker.ubuntu/blob/master/tasks/main.yml

#- name: add Docker key
#  apt_key:
#    id: '2C52609D'
#    url: 'http://get.docker.com/gpg'
#    validate_certs: no
#
#
#- name: Add Docker repository
#  apt_repository:
#    repo: "deb https://apt.dockerproject.org/repo ubuntu-{{ ansible_distribution_release }} main"

- name: run docker script
  shell: 'curl -sSL https://get.docker.com/ | sh'
  args:
    creates: '/etc/default/docker'

- name: install latest docker package
  apt:
    name: 'docker-engine=1.13.*'
    update_cache: yes
    state: 'present'

- name: configure dockerd options
  lineinfile:
    destfile: '/lib/systemd/system/docker.service'
    regexp: '^ExecStart='
    line: 'ExecStart=/usr/bin/dockerd -H fd:// --storage-driver=overlay'
  notify: 'restart docker'

- name: start docker service
  systemd:
    state: started
    name: docker
    daemon_reload: yes

- name: add users to the docker group
  user:
    name: "{{ item }}"
    groups: docker
    append: yes
  with_items: "{{ docker_group_members }}"
  when: docker_group_members is defined

- name: "pull images"
  shell: "docker pull {{ item }}"
  register: register_docker_frontend_image_status
  changed_when: "'Image is up to date' not in register_docker_frontend_image_status.stdout"
  with_items:
    - 'jekyll/jekyll:3.2.1'
    - 'centos:centos7.3.1611'
    - 'cgswong/aws:latest'
    - 'elasticsearch:2.4.1'
    - 'mongo:3.4.2'
    - 'hello-world:latest'


# Add docker compose

- name: create compose dir
  file:
    path: /opt/docker-compose
    state: directory
    mode: 0755

# 1.11.0 use v3 specification for working with docker-engine >= 1.13
- name: download docker compose
  get_url:
    url: https://github.com/docker/compose/releases/download/1.11.0/docker-compose-Linux-x86_64
    dest: /opt/docker-compose/compose

- name: give permissions for compose binary
  file:
    path: /opt/docker-compose/docker-compose
    state: file
    mode: 0775

- name: add compose to system path
  copy:
    dest: '/etc/profile.d/docker-compose.sh'
    content: 'export PATH=/opt/docker-compose:$PATH'

