---

- name: add user
  user:
   name: '{{ home_user }}'

- name: uncomment color for terminal
  become_user: '{{ home_user }}'
  replace:
    dest: '~/.bashrc'
    regexp: '^#force_color_prompt=yes$'
    replace: 'force_color_prompt=yes'
    backup: yes

- name: create ssh dir
  become_user: '{{ home_user }}'
  file:
    path: '~/.ssh'
    state: directory
    mode: 0755

- name: add ssh config
  become_user: '{{ home_user }}'
  template: src=ssh/config dest=~/.ssh/config
