---

- name: add oracle java repo
  apt_repository:
    repo: 'ppa:webupd8team/java'

- name: automatically accept the oracle license
  debconf: name="oracle-java8-installer" question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'

- name: install latest orcale java 8 package
  apt:
    name: 'oracle-java8-installer'
    update_cache: yes
    state: latest

- name: install maven
  apt:
    name: 'maven'
