---

- name: create dir for packer binaries
  file:
    path: '/opt/packer'
    state: directory
    mode: 0755

- name: add packer to system path
  copy:
    dest: '/etc/profile.d/packer.sh'
    content: 'export PATH=/opt/packer:$PATH'

- name: download packer deb
  get_url:
    url: 'https://releases.hashicorp.com/packer/0.10.2/packer_0.10.2_linux_amd64.zip'
    dest: '/tmp/packer_0.10.2_linux_amd64.zip'
    sha256sum: '86c78bae6bd09afb4ddb86915cb71a22fb81ea79578bbf65de3ef48c842d9b2b'
  notify: packer unzip

