---

- name: create dir for packer binaries
  file:
    path: '/opt/packer'
    state: directory
    mode: 0755

- name: add packer to system path
  lineinfile:
    dest: '/etc/bash.bashrc'
    line: 'export PATH=/opt/packer:$PATH'

- name: download packer deb
  get_url:
    url: 'https://dl.bintray.com/mitchellh/packer/packer_0.8.6_linux_amd64.zip'
    dest: '/tmp/packer_0.8.6_linux_amd64.zip'
    sha256sum: '2f1ca794e51de831ace30792ab0886aca516bf6b407f6027e816ba7ca79703b5'
  notify: packer unzip

