---

- name: install python package
  apt: name=python state=latest

- name: install pip package
  apt: name=python-pip state=present

# work: pip install --upgrade pip
- name: update pip
  become_user: '{{ home_user }}'
  pip:
    name: 'pip'
    version: 8.1.2
    state: present

- name: install virtualenv
  pip: name={{item}}
  with_items:
    - virtualenv
    - virtualenvwrapper

- name: create venvs dir
  become_user: '{{ home_user }}'
  file:
    path: '~/{{ python_virtualenv_root }}'
    state: directory
    mode: 0755

- name: add workon_home var
  become_user: '{{ home_user }}'
  lineinfile:
    dest: '~/.bashrc'
    line: 'export WORKON_HOME={{ python_virtualenv_root }}'

- name: add virtualenvwrapper source
  become_user: '{{ home_user }}'
  lineinfile:
    dest: '~/.bashrc'
    insertafter: 'WORKON_HOME'
    line: 'source /usr/local/bin/virtualenvwrapper.sh '

- name: create the virtualenv
  become_user: '{{ home_user }}'
  shell: 'source /usr/local/bin/virtualenvwrapper.sh && mkvirtualenv firstenv'
  environment:
    WORKON_HOME: '{{ python_virtualenv_root }}'
  args:
    executable: /bin/bash
    creates: '~/{{ python_virtualenv_root }}/firstenv'


