---

- name: download vagrant deb
  get_url:
    url: 'https://releases.hashicorp.com/vagrant/1.8.6/vagrant_1.8.6_x86_64.deb'
    dest: '/tmp/vagrant_1.8.6_x86_64.deb'
    sha256sum: 'e6d83b6b43ad16475cb5cfcabe7dc798002147c1d048a7b6178032084c7070da'

- name: install vagrant package
  apt:
    deb: '/tmp/vagrant_1.8.6_x86_64.deb'
    state: present


