---

- name: add virtualbox key
  apt_key:
    url: 'https://www.virtualbox.org/download/oracle_vbox_2016.asc'

- name: add virtualbox repo
  apt_repository:
    repo: "deb http://download.virtualbox.org/virtualbox/debian {{ ansible_distribution_release }} contrib"

- name: install virtualbox package
  apt:
    name: 'virtualbox-5.1'
    # allow_unauthenticated: yes
    update_cache: yes
    state: present

- name: download virtualbox ext pack
  get_url:
    url: 'http://download.virtualbox.org/virtualbox/5.1.6/Oracle_VM_VirtualBox_Extension_Pack-5.1.6-110634.vbox-extpack'
    dest: '/root/apps/Oracle_VM_VirtualBox_Extension_Pack-5.1.6-110634.vbox-extpack'
  register: vb_ext_result

- name: install virtualbox ext pack
  shell: 'sudo VBoxManage extpack install /root/apps/Oracle_VM_VirtualBox_Extension_Pack-5.1.6-110634.vbox-extpack'
  when: vb_ext_result.changed

# faced that virtualbox 5 don't work on ubuntu 16.04
# ugly workaround: disabling secure boot in the BIOS.