---

- name: add virtualbox key
  apt_key:
    url: 'http://download.virtualbox.org/virtualbox/debian/oracle_vbox.asc'

- name: add virtualbox repo
  apt_repository:
    repo: "deb http://download.virtualbox.org/virtualbox/debian {{ ansible_distribution_release }} contrib"

- name: install virtualbox package
  apt:
    name: 'virtualbox-5.1'
    update_cache: yes
    state: present

- name: download virtualbox ext pack
  get_url:
    url: 'http://download.virtualbox.org/virtualbox/5.1.6/Oracle_VM_VirtualBox_Extension_Pack-5.1.6-110634.vbox-extpack'
    dest: '/tmp/Oracle_VM_VirtualBox_Extension_Pack-5.1.6-110634.vbox-extpack'
  register: vb_ext_result

- name: install virtualbox ext pack
  shell: 'sudo VBoxManage extpack install /tmp/Oracle_VM_VirtualBox_Extension_Pack-5.1.6-110634.vbox-extpack'
  when: vb_ext_result.changed
