---
# handlers file for ansible-my_ubuntu_desktop

- name: restart network-manager
  service:
    name: network-manager
    state: restarted

# TODO replace it by 'unarchive' module
- name: packer unzip
  shell: unzip /tmp/packer_0.10.2_linux_amd64.zip-d /opt/packer

- name: terraform unzip
  shell: unzip /tmp/terraform_0.7.4_linux_amd64.zip -d /opt/terraform
