---
# handlers file for ansible-my_ubuntu_desktop

- name: restart network-manager
  service:
    name: network-manager
    state: restarted

- name: restart docker
  systemd:
    name: docker
    state: restarted
    daemon_reload: yes